### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by willy-r** [willy-r/aluraflix#1]
- [ ] Add dark mode/light mode.
- [ ] Add a link to this GitHub repo.
- [ ] Make the site responsive (still learning).
- [ ] Replace letter X to \&times; entity to close button of the modal.
- [ ] Change the module `js/crawler.js` to `js/wrapper.js`, because is a *wrapper* not a crawler.
- [ ] Change the `@import` from CSS to multiple `<link>` in the HTML, because `@import` is slower.
- [ ] Improve accessibility.
- [ ] Refact components.
